export const authConstants = {
  // REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',

  // LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  USER_LOADED: 'AUTH_USER_LOADED',
  LOGOUT: 'AUTH_USER_LOGOUT',
  ERROR: 'AUTH_ERROR',
};
