export const companyConstants = {
  GET_COMPANIES_REQUEST: 'COMPANY_GET_COMPANIES_REQUEST',
  GET_COMPANIES_SUCCESS: 'COMPANY_GET_COMPANIES_SUCCESS',
  GET_COMPANY_REQUEST: 'COMPANY_GET_COMPANY_REQUEST',
  GET_COMPANY_SUCCESS: 'COMPANY_GET_COMPANY_SUCCESS',
  CREATE_COMPANY: 'COMPANY_CREATE_COMPANY',
  DELETE_COMPANY: 'COMPANY_DELETE_COMPANY',
  ERROR: 'COMPANY_ERROR',
};
