export const documentsConstants = {
  GET_DOCUMENTS_REQUEST: 'DOCUMENTS_GET_DOCUMENTS_REQUEST',
  GET_DOCUMENTS_SUCCESS: 'DOCUMENTS_GET_DOCUMENTS_SUCCESS',
  DELETE_DOCUMENT: 'DOCUMENTS_DELETE_DOCUMENT',
  CREATE_DOCUMENT: 'DOCUMENTS_CREATE_DOCUMENT',
  CLEAR_DOCUMENTS: 'DOCUMENTS_CLEAR_DOCUMENTS',
  ERROR: 'DOCUMENTS_ERROR',
};
