export const employeesConstants = {
  GET_EMPLOYEES_REQUEST: 'EMPLOYEES_GET_EMPLOYEES_REQUEST',
  GET_EMPLOYEES_SUCCESS: 'EMPLOYEES_GET_EMPLOYEES_SUCCESS',
  GET_EMPLOYEE_REQUEST: 'EMPLOYEES_GET_EMPLOYEE_REQUEST',
  GET_EMPLOYEE_SUCCESS: 'EMPLOYEES_GET_EMPLOYEE_SUCCESS',
  DELETE_EMPLOYEE: 'EMPLOYEES_DELETE_EMPLOYEE',
  CREATE_EMPLOYEE: 'EMPLOYEES_CREATE_EMPLOYEE',
  CLEAR_EMPLOYEES: 'EMPLOYEES_CLEAR_EMPLOYEES',
  ERROR: 'EMPLOYEES_ERROR',
};
