export const positionsConstants = {
  CREATE_POSITION: 'POSITIONS_CREATE_POSITION',
  GET_POSITIONS_REQUEST: 'POSITIONS_GET_POSITIONS_REQUEST',
  GET_POSITIONS_SUCCESS: 'POSITIONS_GET_POSITIONS_SUCCESS',

  // GET_EMPLOYEE_REQUEST: 'EMPLOYEES_GET_EMPLOYEE_REQUEST',
  // GET_EMPLOYEE_SUCCESS: 'EMPLOYEES_GET_EMPLOYEE_SUCCESS',
  DELETE_POSITION: 'POSITIONS_DELETE_POSITION',
  // CREATE_EMPLOYEE: 'EMPLOYEES_CREATE_EMPLOYEE',
  // CLEAR_EMPLOYEES: 'EMPLOYEES_CLEAR_EMPLOYEES',
  CLEAR_POSITIONS: 'POSITIONS_CLEAR_POSITIONS',
  ERROR: 'POSITIONS_ERROR',
};
