export const profileConstants = {
  GET_REQUEST: 'PROFILE_GET_REQUEST',
  GET_SUCCESS: 'PROFILE_GET_SUCCESS',
  GET_PROFILES: 'PROFILE_GET_PROFILES',
  ERROR: 'PROFILE_ERROR',
  CLEAR: 'PROFILE_CLEAR',
};
